language: ruby
sudo: false
before_install:
  - export LD_LIBRARY_PATH=/usr/lib/llvm-${LLVM_VERSION}/lib/
  - export PATH=/usr/lib/llvm-${LLVM_VERSION}/bin:$PATH
matrix:
  include:
    # The default build:
    - &libclang-36
      addons: {apt: {sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise-3.6], packages: [libclang-3.6-dev, clang-3.6]}}
      env: LLVM_VERSION=3.6
      rvm: "2.3.0"
    # A second build with the same configuration but using ruby 2.2.4
    - <<: *libclang-36
      rvm: "2.2.4"
    # Other builds on other versions of LLVM, all using ruby 2.3.0
    - addons: {apt: {sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise-3.7], packages: [libclang-3.7-dev, clang-3.7]}}
      env: LLVM_VERSION=3.7
      rvm: "2.3.0"
    - addons: {apt: {sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise-3.8], packages: [libclang-3.8-dev, clang-3.8]}}
      env: LLVM_VERSION=3.8
      rvm: "2.3.0"